proxy:
  secretToken: '24427e0459947f9716676e4b8d061d3ad54674f62991be4742485e70a2f8c4d6'
  service:
    type: ClusterIP
singleuser:
  storage:
    dynamic:
      storageClass: local-storage
ingress:
  enabled: true
  hosts:
    - myfedora.yxu.com
  annotations:
    kubernetes.io/tls-acme: "true"
  tls:
    - hosts:
      - myfedora.yxu.com
      secretName: myingress-cert
