apiVersion: apps/v1
kind: Deployment
metadata:
  name: base-notebook
  labels:
    app: notebook
spec:
  selector:
    matchLabels:
      app: notebook
  replicas: 1
  template:
    metadata:
      labels:
        app: notebook
    spec:
      containers:
      - name: base-notebook
        image: docker.io/yxun/base-notebook:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8888
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8888
