apiVersion: v1
kind: Service
metadata:
  name: base-notebook
  labels:
    app: notebook
spec:
  ports:
  - port: 8082
    targetPort: 8888
    nodePort: 30082
  selector:
    app: notebook
  type: NodePort
